### ISSUE TITLE
Could I set pdf page background-color to none-white?

### ISSUE THREAD

**Issue by Jeremyyang** [simonhaenisch/md-to-pdf#102]
**Problem:**

I want to set the pdf page background to anther color, for example black, I got no result even though I googled for 5hours...

`printBackground: true` with background-color just works on `<html>`, but pdf page marge is still white. I am very confused what should I do.

**Comment by simonhaenisch** [comment]
Hey i'm not sure why `printBackground` wouldn't work... can you show how exactly you're setting it? Can you try

```
md-to-pdf my-file --pdf-options '{ "printBackground": true }'
```

**Comment by simonhaenisch** [comment]
Hey again @Jeremyyang, I just had another look at your question and I misunderstood your problem the first time. I thought `printBackground` wasn't working at all for you. Also, `printBackground` is `true` by default anyway.

I was hoping you could use page media css rules (see https://www.w3.org/TR/css-page-3/#page-selector-and-context) for that:

```css
@page {
  background-color: black;
}
```

but sadly it doesn't seem to work. Did a search and seems that Chromium just doesn't support it yet (see https://github.com/puppeteer/puppeteer/issues/5613). There's a reference to try https://www.pagedjs.org/ which is a JavaScript polyfill for it, maybe you can get that to work (you can add scripts to your markdown, either in the content or via config).

Otherwise, the only solution I can think of is removing the margins and adding padding to the `body` element instead.

```markdown
---
pdf_options:
  margin: 0
css: 'body { background-color: black; padding: 30mm 25mm }'
---

However this solution is only good for single-page documents, I guess (because there won't be any padding in between pages). You'll probably also have to stretch the body to 100% height.

Closing this for now but feel free to add comments if you find something out, and I'll consider re-opening.

**Comment by Jeremyyang** [comment]
Thank you very much for your reply, your help is very useful to me!

I just want to change the default white background to an eye-comfortable color. Yes, the following codes take some troubles to the header or the footer of the pdf.
```
---
pdf_options:
  margin: 0
css: 'body { background-color: black; padding: 30mm 25mm }'
---
```

Maybe `page.js` is the right answer while I'll give a try later.

Finally thank you again！😄
