### ISSUE TITLE
bug:  --basedir not working

### ISSUE THREAD

**Issue by electricbritt** [simonhaenisch/md-to-pdf#104]
**Context:**

- version (`md-to-pdf -v`): `5.0.1`
- platform (Unix, macOS, Windows): macOS `10.15.7 `
- node version: `v17.0.1`

**Describe the bug:**

When I add the `--basedir` argument, no changes are made to .pdf output file paths.

```bash
~
❯ cd code                                                     [Monday | 2021-12-13 | 4:16:27 PM EST]

~/code
❯ mkdir pdf                                                   [Monday | 2021-12-13 | 4:16:30 PM EST]

~/code
❯ touch foo1.md  foo2.md foo3.md foo4.md foo5.md              [Monday | 2021-12-13 | 4:16:39 PM EST]

~/code
❯ md-to-pdf *.md --basedir=pdf                                [Monday | 2021-12-13 | 4:17:03 PM EST]
  ✔ generating PDF from foo1.md
  ✔ generating PDF from foo2.md
  ✔ generating PDF from foo3.md
  ✔ generating PDF from foo4.md
  ✔ generating PDF from foo5.md

~/code
❯ ls *.pdf                                                    [Monday | 2021-12-13 | 4:17:11 PM EST]
foo1.pdf       foo2.pdf        foo3.pdf        foo4.pdf        foo5.pdf

~/code
❯ ls pdf                                                      [Monday | 2021-12-13 | 4:17:15 PM EST]

```

**Comment by simonhaenisch** [comment]
I think you might have misunderstood the use case for the `--basedir` option... it's meant for resolving relative paths that you have in your markdown, e. g. references to image files.

Let's say:

- you have a folder called `my-project` and in there you have your `file.md` and another folder called `img`
- in your markdown you reference images with relative paths like `![image 1](./img/image-1.png)`
- now instead of running `md-to-pdf` inside the `my-project` folder, you run it from the parent folder:  
`md-to-pdf my-project/file.md`
- in this case, the relative `./img` path would be incorrect, because it's based on `cwd` (which is the default value for `--basedir`)
- that's why you'd have to give it the correct path to use as the base dir:  
`md-to-pdf my-project/file.md --basedir my-project`

**Comment by electricbritt** [comment]
Aha- many thanks for the clarification.

**Comment by simonhaenisch** [comment]
BTW for what you're trying to achieve, you can use the programmatic API to define the path to the output file per input file.
