### ISSUE TITLE
Installation and usage issue

### ISSUE THREAD

**Issue by nekloth** [simonhaenisch/md-to-pdf#11]
Hello

I'm must be idiot or cursed, but either standard installation and usage does not work... :-/

I'm truing to use md-to-pdf on a Windows 7 and the Ubuntu subsystem of Windows

### Installation issue
Following the procedure, on both Windows and subsys Ubuntu, I used the command line ```npm i -g``` in the github-cloned folder.

Everything went well.

Then, typed ```md-to-pdf readme.md``` and got a:
```md-to-pdf: command not found``` for both systems.

### Usage issue
So, I used ```node c:\temp\md-to-pdf\index.js readme.md``` (Windows 7) or ```node /mnt/c/temp/md-to-pdf/index.js readme.md``` (Ubuntu subsytem) and then, I got (for both):
```{ AssertionError [ERR_ASSERTION]: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'```

### PhantomJs issue

THEN, I tried to install PhantomJS on both system using ```npm install -g phantomjs-prebuilt@2.1.3``` ... and got the same error for both:
```
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1526975751906/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1526975751906/phantomjs-2.1.1-linux-x86_64',
  dest: '/usr/lib/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1526975751906/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/phantomjs-prebuilt/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

May you have an suggestion?

**Comment by simonhaenisch** [comment]
Thanks for the feedback, I found this related issue: Medium/phantomjs#707

Seems that there is no fix yet except using the `—unsafe-perm` flag when installing phantomjs, or some had better luck using yarn instead of npm...

Maybe it’s time to switch to headless Chrome, which requires Chrome to be installed by the user but then we could get rid of the `phantomjs` dependency... phantomjs is not being maintained much anymore and builds are failing on more and more platforms with newer node versions.

Not sure whether that’ll fix the NPM issues though... I’ll look into it again later today. Could you please let me know which NPM version you are using? There is also an issue going on with downtime of the npm registry at the moment, but don’t think it’s related.

**Comment by nekloth** [comment]
My Windows NPM version is 6.0.1
My Ubuntu NPM version is 6.0.1

I tried the --unsafe-perm flag, with the same result...

Windows:
```
Copying extracted folder C:\Users\myname\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1527000866584\phantomjs-2.1.1-windows -> C:\Users\myname\AppData\Roaming\npm\node_modules\phantomjs\lib\phantom
chmod failed: phantomjs was not successfully copied to C:\Users\myname\AppData\Roaming\npm\node_modules\myname\lib\phantom\phantomjs.exe
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@2.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Ubuntu:
```
$ sudo npm install -g phantomjs@2.1.1 --unsafe-perm
npm WARN deprecated phantomjs@2.1.1: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! path /usr/lib/node_modules/phantomjs/node_modules/fs-extra
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/phantomjs/node_modules/fs-extra' -> '/usr/lib/node_modules/phantomjs/node_modules/.fs-extra.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

I confirm: I'm cursed ! :-)

**Comment by simonhaenisch** [comment]
Would you mind trying with node 8/npm 5? With node 10/npm 6 I ran into some issues with packages as well...

**Comment by simonhaenisch** [comment]
Just a heads up: I had another idea of using Electron to render and print the PDF (because it wouldn't require Chrome to be installed and uses the same rendering engine, Chromium), but it turned out that would be a major refactoring because I would need to wrap the whole program inside an Electron process. Also, Electron's [`printToPDF` options](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsprinttopdfoptions-callback) are quite limited regarding page formatting.

I'll give headless chrome a try later and then see whether I can add `phantomjs` as an optional dependency for people who don't have Chrome.

**Comment by nekloth** [comment]
Thank you for the update, but I have Chrome installed so ... I don't know if it will help.

I wasn't able to test node 8/npm 5 (cannot do what I want on my corporate computer). However, there is something better now:

I still cannot call "md-to-pdf" or "mdtopdf", but when I ran the process using ```node index.js ...```. It may work as I sometimes have PhantomJS timeouts.

**Comment by simonhaenisch** [comment]
could you please try whether the latest release works on windows?
