### ISSUE TITLE
bug: missing non-english word in Github Actions

### ISSUE THREAD

**Issue by zizifn** [simonhaenisch/md-to-pdf#110]
**Context:**

- version 5.0.1:
- platform (Github Actions):
- node version: 16

**Describe the bug:**
Seems md-to-pdf missing non-english word in github actions

A clear and concise description of what the bug is. Feel free to include screenshots.
Missing non-english word in github actions

**Comment by simonhaenisch** [comment]
🤷🏻‍♂️

**Comment by zizifn** [comment]
@simonhaenisch anyway to fix this, it works in my Windows 11 machine, but not in Github Actions

**Comment by simonhaenisch** [comment]
I have no idea what exactly happens and why... the issue description has no details at all, so how would you think I could do anything to solve this? My best guess is that the machine that runs the Github Action doesn't have a font for special characters or sth like that? Are you using `utf-8` encoding and unicode characters?

Why wouldn't you be able to simply provide the non-english word that isn't being rendered? Otherwise there's nothing I can do except guessing around, sorry (and I don't really have time for that).

**Comment by YoshihikoFuruhashi** [comment]
I think you need to specify a Chinesefont and install it to runner.
Like below:

- Override font-family with a Chinese font

    ```md
    css: |-
      .markdown-body { font-size: 11px; font-family: <your-chinese-font>, sans-serif;}
    ```

- Install a chinese font to GitHub Actions runner

  ```yml
  steps:
    - name: Install Chinese font
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y <your-chinese-font>
  ```
