### ISSUE TITLE
feature: Single page export

### ISSUE THREAD

**Issue by superpupervlad** [simonhaenisch/md-to-pdf#118]
**Problem:**
Because of long code blocks and images pages might have a big empty spaces or breaks in wrong places.
![image](https://user-images.githubusercontent.com/6016099/156787037-62470868-a648-4a42-82ce-6ae7ff049659.png)

**Solution:**
I would like to generate pdf file with one long page, so it will look exactly like it looks in text editor: without separating into pages and empty spaces.
It can be implement as option for pdf-options flag: `--pdf-options '{ "format": "One page"}'`

**Comment by simonhaenisch** [comment]
Sorry, that's not how PDF works, it automatically inserts page breaks depending on the page size.

Possible solutions:

- use the `--as-html` flag, because there's no such thing as page breaks for HTML docs
- instead of setting a `format`, use the `width` and `height` PDF options, e. g. `{ "width": "21cm", "height": "999cm" }` (you'd have to play around with the hight until you find the one you need to fit your whole doc)
- Manually add page breaks before things that you don't want to break across pages (see [readme#page-break](https://github.com/simonhaenisch/md-to-pdf#page-break))

**Comment by adam-kiss-sg** [comment]
Hi!

I would be interested in this feature as well. Based on https://github.com/puppeteer/puppeteer/issues/475#issuecomment-324693131 I think it would be possible to implement this, although it's probably not as trivial as it sounds because of page width and margins.

@simonhaenisch would you consider re-opening this feature request?

**Comment by simonhaenisch** [comment]
Hey sry, I don't have capacity to work on this. You can fork it and try it yourself. If it works for you and it's generic enough, you can open a PR to add the feature if you want 🤓
