### ISSUE TITLE
bug: highlight.js broken on Vercel

### ISSUE THREAD

**Issue by codingwithdidem** [simonhaenisch/md-to-pdf#121]
Locally converting from markdown to html and pdf works perfectly but when I deploy on Vercel
Highlight css files are not found .

- version (`md-to-pdf -v`): 5.1.0
- platform (Unix, macOS, Windows): macOS
- node version:  16.13.1

I defined **tokyo-night-dark** as the highlight style and its working locally
<img width="579" alt="Screen Shot 2022-04-17 at 20 12 35" src="https://user-images.githubusercontent.com/78794523/163725183-1bf48e68-62d5-408e-a522-b96cf8b9668b.png">

but on production with vercel I got this error :
<img width="918" alt="Screen Shot 2022-04-17 at 20 08 48" src="https://user-images.githubusercontent.com/78794523/163725065-5c4c4741-6748-4b74-b45a-adfac43f09bd.png">

**Comment by simonhaenisch** [comment]
Nice, I didn't even know it's possible to run this on Vercel.

I just did a local `ls node_modules/highlight.js/styles` and I don't actually see any `tokyo-night-dark.css` there, so probably you have a newer version of `highlight.js` installed locally? Just checked and that color scheme not in 11.3 but appears to be in 11.5.

It might be due to the fact that you use a different `npm` version locally, or maybe Vercel uses `npm ci` which installs exactly what's pinned in `package-lock.json`. Vercel doesn't offer Node 16 yet, and Node 14 comes with npm 7 not 8. Maybe you can solve this though by deleting your `package-lock.json`, then running `npm install` again, and pushing the changes of the package-lock.
