### ISSUE TITLE
Question: How to make "*.md" work for Win10?

### ISSUE THREAD

**Issue by Zony-Zhao** [simonhaenisch/md-to-pdf#130]
![image](https://user-images.githubusercontent.com/50739849/184467499-3f2d2693-26de-4b42-a36a-8970c870708b.png)
It seems that * .md file just doesnt work in powershell. Is there any alternates?

**Comment by simonhaenisch** [comment]
I'm not very familiar with PowerShell's globbing but according to the [docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-7.2) it should work like this 🤷🏻‍♂️ maybe you need to check your shell's config?

Anyway, you can just omit the `*.md` because by default it'll convert all `.md` files in the current directory iirc.
