### ISSUE TITLE
volernability issue - minimatch library version 3.0.4 is not safe

### ISSUE THREAD

**Issue by hadasmeitav** [simonhaenisch/md-to-pdf#151]
**Context:**

- version : 5.2.1 (latest)
- platform: macOS
- node version: 16.13.2

As a sub-dependency, you're using `serve-handler` library, which uses `minimatch` library. 
`minimatch` [3.0.4 version is volernable](https://github.com/advisories/GHSA-f8q6-p94x-37v3). 
Can we update `serve-handler` version so that this vulnerability issue won't apply to my code? 

Thanks in advance 🙏

**Comment by simonhaenisch** [comment]
Ok but just so you're aware there's no way to actually exploit this vulnerability since as an end user you don't have any control over the input that is vulnerable (requested path). So in that sense this vulnerability doesn't apply to your code already.

These vulnerability reports are generally overrated, and it would be appreciated if you only open an issue about it if you can confirm that the vulnerability is relevant (:

**Comment by hadasmeitav** [comment]
you're right, but nevertheless my company can't pass the external security inspection because of this...
