### ISSUE TITLE
bug: vulnerability in path-to-regexp dependency

### ISSUE THREAD

**Issue by dmattia** [simonhaenisch/md-to-pdf#316]
**Context:**

- version (`md-to-pdf -v`):  5.2.4
- platform (Unix, macOS, Windows): all
- node version: all

**Describe the bug:**

md-to-pdf depends on serve-handler: https://github.com/simonhaenisch/md-to-pdf/blob/master/package.json#L58C6-L58C19, which has a HIGH severity bug that has not been patched for over a month: https://github.com/vercel/serve-handler/issues/211

Could md-to-pdf find another dependency to use, or otherwise resolve this open vulnerability?

**Comment by simonhaenisch** [comment]
I'd say you can safely ignore this vulnerability since it's not exploitable, unless you somehow expose the underlying web server created by md-to-pdf to end users for some reason which will probably give you much bigger security problems than a regex ddos...

If you can actually make a good case for replacing it (explaining how the vulnerability is exploitable) then ok i can look into it. If it's just to quieten npm audit then sorry but i'll ignore it until serve-handler is fixed itself 🙃
