### ISSUE TITLE
Automatically Expand <details> Blocks

### ISSUE THREAD

**Issue by shellscape** [simonhaenisch/md-to-pdf#33]
Wonderful project, thank you.

I'd like to request automatically expanding <details> blocks in markdown files. These are frequently used to expand/hide sections such as Tables of Contents.

**Comment by simonhaenisch** [comment]
It's relatively simple to do that by using the [`open`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#Attributes) attribute on it:

---

```html
<details open>
  Hello
</details>
```

<details open>
  Hello
</details>

---

Is that good enough for you?

Otherwise I can add a script that would basically do

```js
document.querySelectorAll('details').forEach(details => (details.open = true))
```

to open all details on the page automatically.

**Comment by shellscape** [comment]
I think the `open` attribute will suffice nicely. Thank you.

**Comment by e2045** [comment]
Hi, I have a problem with details block. Details block doesn't expand in my pdf. How could I handle it?

**Comment by jnaklaas** [comment]
If I don't want to open it by default, only when exported to pdf? Otherwise there's no point in using `<details>`.
Is it possible by adding that script somewhere? It's not clear how to add a script.

**Comment by simonhaenisch** [comment]
@jnaklaas just inject the script I mentioned at the end of your markdown... md-to-pdf supports html-in-markdown (otherwise you wouldn't be able to add `<details>` either, right).
