### ISSUE TITLE
Clipping on edges with numbered lists > 9.

### ISSUE THREAD

**Issue by naderm** [simonhaenisch/md-to-pdf#36]
I have been seeing weird clipping issues on PDFs with numbered lists ranging above 9. Oddly, this appears to only happen during Linux builds on our CI, see [Cell_Culture.pdf](https://github.com/white-lab/protocols/releases/download/2019-06-03/Cell_Culture_Protocols.pdf)

But not when running `md-to-pdf` on Windows, see: [Cell_Culture.pdf](https://github.com/simonhaenisch/md-to-pdf/files/3254902/Cell_Culture.pdf)

[Here is the config file used to generate these PDFs](https://github.com/white-lab/protocols/blob/master/md_to_pdf.json)

Would this be an issue with md-to-pdf? Or something upstream?

**Comment by simonhaenisch** [comment]
Sounds like an upstream bug with marked... would you be able to run just marked on that CI system and see what the generated html looks like?

Do you have some more information what linux version your CI is running?

**Comment by simonhaenisch** [comment]
Sorry it's been so long... this was not actually an upstream issue but because the stylesheet didn't give any left margin to the list. I forgot about this issue until I saw it triaging on the project board today 🙈 I've fixed it and will release it with the v3 release (in a couple weeks). Unless you need it, then I can patch the current version.
