### ISSUE TITLE
Blank lines not keeped

### ISSUE THREAD

**Issue by salmonjean** [simonhaenisch/md-to-pdf#45]
Hi Simon!

Why blank lines (ie those only with carriage return & Lien Feed) are _deleted_ during conversion ?
```
# Title One 
## Subtitle 

One sentence after blank line.


An another one sentence after 2 blank lines.
```

![image](https://user-images.githubusercontent.com/53435419/63698597-71c83b80-c81f-11e9-94a2-fbcc91442343.png)
![image](https://user-images.githubusercontent.com/53435419/63699138-8a852100-c820-11e9-800f-4d16cc327386.png)

**Comment by simonhaenisch** [comment]
https://daringfireball.net/projects/markdown/syntax#p

> A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines. (A blank line is any line that looks like a blank line — a line containing nothing but spaces or tabs is considered blank.) Normal paragraphs should not be indented with spaces or tabs.
>
> The implication of the “one or more consecutive lines of text” rule is that Markdown supports “hard-wrapped” text paragraphs. This differs significantly from most other text-to-HTML formatters (including Movable Type’s “Convert Line Breaks” option) which translate every line break character in a paragraph into a `<br /> tag.
>
> When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.
>
> Yes, this takes a tad more effort to create a `<br />`, but a simplistic “every line break is a `<br />`” rule wouldn’t work for Markdown. Markdown’s email-style blockquoting and multi-paragraph list items work best — and look better — when you format them with hard breaks.

**Comment by simonhaenisch** [comment]
BTW when you create an issue here, you see this page:

![image](https://user-images.githubusercontent.com/3410759/63704986-7d6e2f00-c82c-11e9-9f6e-d49acd757e0c.png)

In the subtitle of the "Bug Report", it tells you to open a regular issue if it's a question not a bug. There's a blue link "Open a regular issue" at the bottom of that. Would you mind doing that? Then your questions won't be labelled as bugs automatically.

And on another matter: please first check the docs of markdown syntax, Marked and Puppeteer when you struggle with something like this. In probably 90% of the cases your issue is related to those underlying tools. The links are in the readme.

**Comment by salmonjean** [comment]
Hi Simon.
I can understand easily that you thought it was just an insignificant request.
Thank you for sending me the original markdown specification. I know it.
The format definition begin by telling that a blank line is any line that _looks like_ a blank line ; 
only "CR + LF" also so.
From my point of view, to delete original lines breaks (CR+LF) is a loss of information.
Your tool is light and practical. 
For this point or another, what will also differentiate your tool from others will be to overcome the shortcomings of the specification. 
That's why I opened an issue.
Sorry to have disturbed you.
Regards,
Jean

**Comment by simonhaenisch** [comment]
No, I disagree.

The specification - depending on which one you use, because there's multiple and no official one - has one or more solutions for this problem.

![image](https://user-images.githubusercontent.com/3410759/63765732-f8d1ee00-c8c9-11e9-96f1-61edb54c31f2.png)

You can also simply insert `<br>` tags because html within markdown is supported.

I found the solution on stackoverflow.com as the first result of searching "markdown two blank lines" on Google. I don't mind helping with questions about the tool I created, and finding solutions for non-trivial problems, but I do mind researching and reading for you. If I notice that you've done that first (which you clearly have not), I'm happy to help.

**Comment by salmonjean** [comment]
Simon,

I know you are not agree.
I just tried to show you an another point of view.

Despite what you think I had already looked at Stackoverflow : https://stackoverflow.com/questions/33191744/how-to-add-new-line-in-markdown-presentation/33191810 for instance.

Thanks to our conversation I just discovered that it was M. Murray (from New Zealand) in 1901 who invented the control characters CR and LF ;  from the work of M. Baudot (a french telegraph engineer) : good team spirit ! ;-)

![330px-Clavier_Baudot](https://user-images.githubusercontent.com/53435419/63770213-ef9a4e80-c8d4-11e9-93dc-d0f2c45cc66d.jpg)
https://en.wikipedia.org/wiki/Carriage_return
https://en.wikipedia.org/wiki/Baudot_code

Have a nice afternoon!
