### ISSUE TITLE
How to generate IDs without accentuated and special characters ?

### ISSUE THREAD

**Issue by salmonjean** [simonhaenisch/md-to-pdf#46]
Hi Simon !
How are you ?

Once again I ask for your help !

As you know, I'm using markdown-toc. 
Links doesn't work for titles with accentuated characters (in html and pdf).
It's a well-known issue (https://github.com/jonschlinkert/markdown-toc/issues/145).

Would it be possible for md-to-pdf to generate IDs without accentuated and special characters (in order to be homogenous with the slugify function used) ?

For instance, today we have this title in one markdown file :
```
Un titre de niveau H2 avec 2 caractères accentués
------------
```
Today, with md-to-pdf, the result in Html is :
`<h2 id="un-titre-de-niveau-h2-avec-2-caractères-accentués">Un titre de niveau H2 avec 2 caractères accentués</h2>`

I would like please :
`<h2 id="un-titre-de-niveau-h2-avec-2-caracteres-accentues">Un titre de niveau H2 avec 2 caractères accentués</h2>`
(or 
`<h2 id="un-titre-de-niveau-h2-avec-2-caract-res-accentu-s">Un titre de niveau H2 avec 2 caractères accentués</h2>`
)

![image](https://user-images.githubusercontent.com/53435419/64022006-806f6500-cb35-11e9-93d9-9e4c00818f17.png)

Thanks in advance!

Jean

**Comment by simonhaenisch** [comment]
Yes this would be possible by extending the renderer with a custom `heading` method. This example from the Marked docs should help you implement it:

https://marked.js.org/#/USING_PRO.md#renderer

However at the moment it's not possible to extend the renderer from the options. I'll make it possible now and release a new version (you'll have to use a `js` file for the options though because you can't set functions from `yaml` or `json`).

**Comment by simonhaenisch** [comment]
Just released `2.8.0`, in which you can pass a custom marked renderer (using a `.js` config file for already mentioned reasons), e. g.:

```js
const marked = require('marked');

const renderer = new marked.Renderer();

render.heading = (text, level) => `<h${level}>${text.replace(/[^\w]+/g, '_')}</h${level}>`;

module.exports = {
  // ...
  marked_options: { renderer },
};
```

adjust the replace regex to what you need (this one would replace all non alphanumeric characters with underscores).

Please let me know if this does not work for you (haven't tested it).

**Comment by salmonjean** [comment]
Hi Simon,

Thank you for being interested by this subject!
I've tried your proposal but it doesn't work.
Headers are not modified in html destination file.

The only string which is replaced is this one of the log.

```
// Run marked
console.log(marked('# un exemple de titre accentué+', { renderer: renderer }));
```
![image](https://user-images.githubusercontent.com/53435419/64105891-5c9b6180-cd77-11e9-95c9-83e449e750de.png)

I downloaded the latest version of your code : 
![image](https://user-images.githubusercontent.com/53435419/64106217-0b3fa200-cd78-11e9-9c75-7e7c08f4e66b.png)

**Comment by simonhaenisch** [comment]
You're only sharing the code that works, so I can't help you with what's not working.

**Comment by salmonjean** [comment]
Hi Simon

I just modified the string as an example.

I only use your code :

```
(...)
const marked = require('marked');
const renderer = new marked.Renderer();
renderer.heading = (text, level) => `<h${level}>${text.replace(/[^\w]+/g, '_')}</h${level}>`;

// Run marked
console.log(marked('# heading+', { renderer: renderer }));

module.exports = {  
  marked_options: { renderer },
  headerTemplate: 
 (...)

```
![image](https://user-images.githubusercontent.com/53435419/64114991-cc691680-cd8e-11e9-8584-270f53276678.png)

**Comment by simonhaenisch** [comment]
Since you still only shared working code, I'm assuming that you're trying to say that it works when you invoke marked but it doesn't work in the html/pdf that is output by the tool? I just tried this out and it works for me.

`config.js`:

```js
const { Renderer } = require('marked');

const renderer = new Renderer();

renderer.heading = (text, level) =>
  `<h${level}>${text.replace('Images', 'Memes')}</h${level}>`;

module.exports = {
  marked_options: { renderer },
};
```

`test.md`:

<img src="https://user-images.githubusercontent.com/3410759/64171049-f59eab00-ce51-11e9-8f4f-1a7d993368c3.png" width="315">

After running `md-to-pdf test.md --config-file config.js`, the pdf looks like

<img src="https://user-images.githubusercontent.com/3410759/64171186-5201ca80-ce52-11e9-9053-5d6cd4bf84e9.png" width="183">

**Comment by salmonjean** [comment]
Hi Simon,

Do you have tried with several levels heading ?

=>_it doesn't work in the html/pdf that is output by the tool?_ 
Exactly, it didn't work!

I've just inserted this code directly into your source code **get-marked-with-highlighter.js** and now it works ! :-) All titles are taken in account!

Don't worry for code replacing accentuated or special characters. You can not imagine from how many years I know regular expressions. (I began with Awk on Unix Digital VAX Station…)
Nevertheless, we learn at any age! ;-)

Thanks for your help!

```
const marked = require('marked');
const { getLanguage, highlight } = require('highlight.js');

/**
 * Get a marked renderer with an attached highlighter.
 *
 * @param {Object} options Marked configuration object
 *
 * @returns a marked renderer with highlight.js parser attached
 */
module.exports = options => {
	const renderer = options.renderer || new marked.Renderer();
	
	/* Added by JSN on 20190903_______________________________________________Begin >>> */
	renderer.heading = function (text, level) {
		console.log("level" + level);
				  
		var escapedText = text.toLowerCase().replace(/[^\w]+/g, '-');

		return '<h' + level + '><a name="' +
                escapedText +
                '" class="anchor" href="#' +
                escapedText +
                '"><span class="header-link"></span></a>' +
                text + '</h' + level + '>';  
	}
	/* Added by JSN 20190903_________________________________________________End <<<  */
	
	if (!renderer.hasOwnProperty('code')) {
		renderer.code = (code, language) => {
			// if the given language is not available in highlight.js, fall back to plaintext
			language = (getLanguage(language) && language) || 'plaintext';

			return `<pre><code class="hljs ${language}">${highlight(language, code).value}</code></pre>`;
		};
	}

	marked.setOptions({ ...options, renderer });

	return marked;
};
```


![image](https://user-images.githubusercontent.com/53435419/64172917-57611400-ce56-11e9-9ff9-272c2e189cf2.png)

**Comment by simonhaenisch** [comment]
Ok, as you can see in that source code, `options.renderer` is the renderer that you pass in through the `marked_options` of the `js` config file... not sure where your mistake is, but I assume that you're not passing that config properly. Are you using `md-to-pdf` through the cli or programmatically? In the latter case, instead of exporting the config, you'll have to pass it into the function call:

```js
const mdToPdf = require('md-to-pdf');

// prepare renderer ...

(async () => {
  const options = {
    dest: 'file.pdf',
    marked_options: { renderer },
  };

  const pdf = await mdToPdf('file.md', options).catch(console.error);

  console.log(pdf.filename);
})();
```

I doubted that it has anything to do with the level of the heading but I gave it a try and it works just fine (with the same replace "Images" with "Memes" function):

| Markdown | PDF |
|-|-|
| <img src="https://user-images.githubusercontent.com/3410759/64176202-3819b500-ce5d-11e9-97bb-48cecb22f127.png" width="315"> | <img src="https://user-images.githubusercontent.com/3410759/64176246-4bc51b80-ce5d-11e9-96c8-1439ff6c3e87.png" width="190"> |

So you're definitely just doing something wrong with how you're passing the renderer.

**Comment by salmonjean** [comment]
Hi Simon,

I reviewed my code. I made an error in the options. It works fine now!
Sorry.
Thanks for your help!

Jean
