### ISSUE TITLE
Avoid strictly pinned version of puppeteer

### ISSUE THREAD

**Issue by danieljuhl** [simonhaenisch/md-to-pdf#62]
I was wondering if it would be possible to avoid a strictly pinned version of puppeteer?

Right now the project is using 2.0.0, but that isn't the latest. And as puppeteer can be pretty heavy with everything installed, I would suggest allow minor updates, and assume puppeteer is semver compatible.

**Comment by simonhaenisch** [comment]
I generally pin down dependencies for apps but not packages because I've had issues in the past with broken apps because of unwanted dependency updates. However in this case I think it's pretty safe to not pin down `puppeteer` because you're right that it follows semantic versioning, and the `page.pdf()` API is stable anyway.

Would you mind explaining how Puppeteer being a heavy dependency is a problem for you and why not pinning down the version solves that?

**Comment by simonhaenisch** [comment]
Unpinned in version `3.0.0-pre.1` (install with `npm install md-to-pdf@next`).

**Comment by danieljuhl** [comment]
@simonhaenisch `puppeteer` downloads a version of Chromium (if this is not disabled), and when having a project that itself uses `puppeteer` and `md-to-pdf` causes multiple versions of `puppeteer` and multiple versions of Chromium.
