### ISSUE TITLE
Including images in a different folder

### ISSUE THREAD

**Issue by gaitat** [simonhaenisch/md-to-pdf#64]
I have an image reference in my md file `![](../images/image.png)` so it is not in the same folder as my markdown document. When from inside the folder I run `md-to-pdf --as-html document.md` then I can see that the image is found. But when I run `md-to-pdf document.md` then the resulting pdf does not contain the image.

**Comment by simonhaenisch** [comment]
Are you using version 2.8 or 3.0 (`npm install md-to-pdf@next`)?

With version 2.8 this is not possible because the markdown file's location is used as the root of the file server. But with version 3, the current working directory becomes the base directory of the file server (changeable with `--basedir` option), which allows to reference images from outside the markdown file's location. Could you give it a try please, and let me know if it works?

If your structure is

```
my-project
|- images
|  |- image.png
|- markdown
|  |- document.md
```

then you'd have to run

```
md-to-pdf markdown/document.md
```

(from the `my-project` dir).

**Comment by gaitat** [comment]
First, let me say great job great software.
Version 3.0 works as I expected.
Usually I dont install pre-alpha software. Any idea when version will become stable?

**Comment by simonhaenisch** [comment]
Was just waiting to see whether anyone would run into issues with version 3. So far it seems like it's been working alright though, so I'll release it within the next week or so, I think.
