### ISSUE TITLE
Question: Why use media "screen" instead of the default "print"?

### ISSUE THREAD

**Issue by MangelMaxime** [simonhaenisch/md-to-pdf#80]
Hello,

when generating a PDF md-to-pdf set the media type to `screen` which prevent us to have specific CSS media rule for print. By default, puppeteer use `print` when no media type is set.

https://github.com/simonhaenisch/md-to-pdf/blob/f9bd305247d94e21e56efafe8837d3d7947401ae/src/lib/generate-output.ts#L41

Is it possible to use `print` media instead or make it configurable? Does using `screen` media solve problems that I don't know?

PS: Sorry for the bug label, I think I created this issue as a bug report instead of a feature request...

**Comment by simonhaenisch** [comment]
It's a good question... I think I just did it in the first version to avoid unwanted effects of the browser's default print styles. The tool should print exactly what you'd see when inspecting the content in the browser.

I've just checked the default stylesheet for Chrome (https://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css) and it doesn't look like there's any `@media print` definitions anyway, so changing it to emulate `print` instead would probably be fine. However I'm not entirely sure and I don't want to break the current behavior, so yeah we can definitely make this configurable.

> Does using `screen` media solve problems that I don't know?

I guess you'll know afterwards 😅 I'm really not sure because it's always been `screen` which seems like it's generally what people want (WYSIWYG).

**Comment by MangelMaxime** [comment]
Thank you for the quick fix :)

I agree that I like the WYSIWYG, its just that each time I search for things like "Html to pdf using puppeteer" I see people using media queries. I think this is because they try to print their website to PDF and so they remove stuff like ads, etc.

**Comment by simonhaenisch** [comment]
Just released 3.2.1 so you can either use `--page-media-type print` as a flag or set `page_media_type: 'print'` in the config.
